import Head from 'next/head';
import Image from 'next/image';
import * as Pokemon from '../components/Pokemon';
import client from '../graphql/client';
import { GET_POKEMONS } from '../graphql/query';

export default function Home(props) {
  const { pokemons = [], pokemontCount = 0 } = props;

  const renderPokemonList = pokemons.map((pokemon, i) => (
    <Pokemon.Item key={i} imageUrl={pokemon.image} name={pokemon.name} owned={0} onClick={() => console.log('test')} />
  ));

  return (
    <div>
      <Head>
        <title>PokeDex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Pokemon.List>{pokemons && renderPokemonList}</Pokemon.List>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { page = 1 } = context.query;
  const { data } = await client.query({
    query: GET_POKEMONS,
    variables: {
      offset: page - 1,
      limit: 10,
    },
  });

  return {
    props: {
      pokemons: data.pokemons.results,
      pokemontCount: data.pokemons.count,
    },
  };
}
