import Head from 'next/head';
import Image from 'next/image';
import { PokemonList, PokemonItem } from '../components/shared/';
import client from '../commons/graphql/client';
import { GET_POKEMONS } from '../commons/graphql/query';

export default function Home(props) {
  const { pokemons = [], pokemontCount = 0 } = props;

  const renderPokemonList = pokemons.map((pokemon, i) => (
    <PokemonItem key={i} {...pokemon} onClick={() => console.log('test')} />
  ));

  return (
    <div>
      <Head>
        <title>PokeDex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PokemonList>{pokemons && renderPokemonList}</PokemonList>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { page = 1 } = context.query;
  const { data } = await client.query({
    query: GET_POKEMONS,
    variables: {
      offset: page - 1,
      limit: 20,
    },
  });

  return {
    props: {
      pokemons: data.pokemons.results,
      pokemontCount: data.pokemons.count,
    },
  };
}
