import Head from 'next/head';
import Image from 'next/image';
import { PokemonOwnedItem } from '../../components/pokemon';
import { Grid } from '../../components/ui/Grid';
import client from '../../commons/graphql/client';
import { GET_POKEMONS } from '../../commons/graphql/query';
import { useContext } from 'react';
import { PokemonContext } from '../../commons/context/pokemon.context';
import Empty from '../../components/ui/Empty';
import Block from '../../components/ui/Block';

export default function Owned() {
  const { pokemons = {} } = useContext(PokemonContext);

  const renderPokemonList = Object.values(pokemons)
    .flat()
    .map((pokemon, i) => <PokemonOwnedItem key={i} {...pokemon} />);

  const renderEmpty =
    Object.keys(pokemons).length === 0 ? (
      <Block>
        <Empty />
      </Block>
    ) : null;

  return (
    <div>
      <Head>
        <title>PokeDex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid xs={2} sm={3} md={4} lg={6}>
        {pokemons && renderPokemonList}
      </Grid>
      {renderEmpty}
    </div>
  );
}
